version: '3.9'

services:
  mariadb:
    image: ${MARIADB_IMAGE}:${MARIADB_VERSION}
    container_name: ${PROJECT_NAME}-mariadb
    environment:
      - TZ=${TZ}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE} 
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_PORT_EXTERNAL}:${MYSQL_PORT}
    restart: always

  mongodb:
    image: ${MONGODB_IMAGE}:${MONGODB_VERSION}
    container_name: ${PROJECT_NAME}-mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - ${MONGO_PORT_EXTERNAL}:${MONGO_PORT}
    restart: always
  
  web:
    restart: always
    container_name: ${PROJECT_NAME}-web
    build:
      context: ../
      dockerfile: ./docker
    expose:
      - 80
      - 443
    env_file:
      - ./conf/env
    ports:
      - ${ANNOTATION_TOOL_HTTP_PORT}:80
      - ${ANNOTATION_TOOL_HTTPS_PORT}:443
    depends_on:
      - mariadb
      - mongodb
    links:
      - 'mariadb'
