# Generated by Django 3.1.7 on 2021-10-10 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clarin_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedcollections',
            name='fromfield',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fromfield', to=settings.AUTH_USER_MODEL, to_field='email'),
        ),
        migrations.AlterField(
            model_name='sharedcollections',
            name='tofield',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tofield', to=settings.AUTH_USER_MODEL, to_field='email'),
        ),
    ]
