# Generated by Django 3.1.7 on 2021-10-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clarin_backend', '0003_auto_20211010_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='first_name',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='first_name'),
        ),
    ]
