# Generated by Django 3.1.7 on 2021-10-10 18:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clarin_backend', '0004_auto_20211010_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collections',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.today, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='collections',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime.today, verbose_name='updated_at'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.today, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime.today, verbose_name='updated_at'),
        ),
        migrations.AlterField(
            model_name='opendocuments',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.today, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='opendocuments',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime.today, verbose_name='updated_at'),
        ),
        migrations.AlterField(
            model_name='sharedcollections',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.today, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='sharedcollections',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime.today, verbose_name='updated_at'),
        ),
        migrations.AlterField(
            model_name='users',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.today, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='users',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime.today, verbose_name='updated_at'),
        ),
    ]
