# Generated by Django 4.1.2 on 2022-10-24 09:50

import clarin_backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clarin_backend', '0008_alter_documents_data_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='data_file',
            field=models.FileField(blank=True, default=None, max_length=255, null=True, upload_to=clarin_backend.models.user_collection_directory_path),
        ),
        migrations.AddField(
            model_name='documents',
            name='data_url',
            field=models.URLField(blank=True, default=None, max_length=512, null=True),
        ),
    ]
